name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Format
        working-directory: ./frontend
        run: npm run format

      - name: Check uncommitted changes
        run: git diff --exit-code

      - if: failure()
        run: echo "::error::Check failed, please run 'npm run format' and commit the changes."

  frontent-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint
        working-directory: ./frontend
        run: npm run lint

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build
        working-directory: ./frontend
        run: npm run build

  server-go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - name: Run go mod tidy
        working-directory: ./server
        run: go mod tidy

      - name: Check uncommitted changes
        run: git diff --exit-code

      - if: failure()
        run: echo "::error::Check failed, please run 'go mod tidy' and commit the changes."

  server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - name: Run go build
        working-directory: ./server
        run: go build
